fullData <- read.csv("./household_power_consumption.txt", sep=";", na.strings="?")
theData <- subset(fullData, Date == "1/2/2007"| Date=="2/2/2007" ,select = c(Date, Global_active_power))
png(filename="plot1.png", width=480, height=480)
hist(theData$Global_active_power, main="Global Active Power", xlab="Global Active Power (kilowatts)", col="red", ylim=c(0,1200))
dev.off()
